apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: monitoring
  name: monitoring
  namespace: kube-system
spec:
  replicas: 1
  selector:
    name: monitoring
  template:
    metadata:
      labels:
        name: monitoring
    spec:
      containers:
      - name: monitoring
        image: caicloud/monitoring:2015-11-26-23-20-21
        imagePullPolicy: Always
