apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring
  name: monitoring
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8091
  selector:
    name: monitoring
